# Generated by Django 4.2.6 on 2023-10-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_corrections_correction_rename_logs_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='log',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
